SELECT DISTINCT P.PATIENT_ID, P.P_FIRST_NAME, P.P_AGE, P.ADDRESS, P.CONTACT_NUMBER
FROM PATIENT P, APPOINTMENT A
WHERE P.PATIENT_ID = A.PATIENT_ID
    AND MONTH(A.APP_DATE) = 6
    AND YEAR(A.APP_DATE) = 2019
ORDER BY P.PATIENT_ID;
