SELECT A.MIN_DISCOUNT, B.MAX_DISCOUNT
FROM (
         SELECT MIN(DISCOUNT_AMOUNT) AS `MIN_DISCOUNT`
         FROM DISCOUNT_MASTER
     ) A,
     (
         SELECT MAX(DISCOUNT_AMOUNT) AS `MAX_DISCOUNT`
         FROM DISCOUNT_MASTER
     ) B;